#!/bin/bash
device=""
port=""

# Parse command line arguments
while (( "$#" )); do
  case "$1" in
    -d|--device)
      device=$2
      shift 2
      ;;
    -p|--port)
      port=$2
      shift 2
      ;;
    *)
      shift
      ;;
  esac
done

# Print process info for debugging
echo "Started fake_pcapCollect for device $device on port $port"

while true; do sleep 999999; done
